# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

strategy:
  matrix:
    PhpVersion71:
      phpVersion: 7.1
    PhpVersion72:
      phpVersion: 7.2
    PhpVersion73:
      phpVersion: 7.3

steps:
- script: |
    sudo add-apt-repository ppa:ondrej/php
    sudo apt-get update
    sudo apt-get install php7.3
    sudo apt-get install php7.3-dom php7.3-xml php7.3-simplexml
    php -version
  displayName: 'Install PHP $(phpVersion)'
  condition: eq(variables['phpVersion'], '7.3')
  
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'
  condition: ne(variables['phpVersion'], '7.3')

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'
  
- script: phpunit
  displayName: 'Run tests with phpunit'
